table FactEmail
	lineageTag: fc87bbd4-9fe2-4e94-906f-eba8c606e5b3

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7e4f2a7-7baa-465b-bc32-1eea7df16935
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column campaign
		dataType: string
		lineageTag: 64bf7bd2-abbc-4538-af8c-e716e551b25d
		summarizeBy: none
		sourceColumn: campaign

		annotation SummarizationSetBy = Automatic

	column sends
		dataType: int64
		formatString: 0
		lineageTag: 948214b8-89ba-48a4-8fe1-13ddbd4f4d14
		summarizeBy: sum
		sourceColumn: sends

		annotation SummarizationSetBy = Automatic

	column opens
		dataType: int64
		formatString: 0
		lineageTag: 6335b666-1c53-4d17-97ae-f067824b9e7f
		summarizeBy: sum
		sourceColumn: opens

		annotation SummarizationSetBy = Automatic

	column clicks
		dataType: int64
		formatString: 0
		lineageTag: 93aa2125-fb18-47e5-abf2-b348e7362a57
		summarizeBy: sum
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	partition FactEmail = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\portfolio\Seminal Artist Group\Marketing_Dashboard_Complete_Dataset_Jan2024_Sep2025.xlsx"), null, true),
				    FactEmail_Sheet = Source{[Item="FactEmail",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactEmail_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", Int64.Type}, {"campaign", type text}, {"sends", Int64.Type}, {"opens", Int64.Type}, {"clicks", Int64.Type}, {"source_system", type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"date", type date}}),
				    #"Columns removed"= Table.SelectColumns(#"Changed Type1",{"campaign","clicks","opens","sends","date"})
				in
				    #"Columns removed"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

