table 'Period Slicer'
	lineageTag: 1cffa85b-a8d6-455d-bb45-2922be00fc7c

	column 'Slicer Options'
		dataType: string
		lineageTag: 24e9b509-0580-4fe7-966f-2098b7f92f20
		summarizeBy: none
		sourceColumn: Slicer Options
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 31173b96-43f3-4972-bc74-91914ac72e2e
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'Period Slicer' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMk9R0lEyVIrViVYysgCxjcBsSwMQ2xjMDsnILFaoTE0sAoqYKMXGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Slicer Options" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Slicer Options", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

